### PR TITLE
Changes to make module work for SCOM 2016

### PR DESCRIPTION
**Pull request by mortenlerudjordet**
Changes I did a long time ago, though as there seem to be some life on this module again I will PR the changes I did to make it work for SCOM 2016. 

I never got the time to check the reporting part, so somebody else has to take on that task.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xscom/10)

### CODE REVIEW

**Comment by johlju** [comment]
Thanks for sending this in! I did an initial review. I will continue once these review comments are resolved/answered. 

---

Reviewed 2 of 9 files at r1.
Review status: 2 of 9 files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 180 at r1](https://reviewable.io/reviews/powershell/xscom/10#-LD1avth4L9jovjJml-9:-LD1avth4L9jovjJml-A:bviuavo) ([raw file](https://github.com/powershell/xscom/blob/da802bcc20cb2602638120fbfc3bba47897b0766/README.md#L180)):*
> ```Markdown
> ## Versions
> 
> ### 1.4.0.0
> ```

We should not add version numbers. That will happen during the release.

---

*[README.md, line 182 at r1](https://reviewable.io/reviews/powershell/xscom/10#-LD1b-M14At6KdQ-ZzRX:-LD1b-M14At6KdQ-ZzRY:b-xax2t) ([raw file](https://github.com/powershell/xscom/blob/da802bcc20cb2602638120fbfc3bba47897b0766/README.md#L182)):*
> ```Markdown
> ### 1.4.0.0
> 
> * Changed to support SCOM 2016
> ```

Please add this entry to the Unreleased section. See a previous comment.

---

*[README.md, line 184 at r1](https://reviewable.io/reviews/powershell/xscom/10#-LD1am160Grm78V2nQ2Y:-LD1am160Grm78V2nQ2Z:b-pc63oe) ([raw file](https://github.com/powershell/xscom/blob/ca8a55886405955df5705617eecbb9a2c8319453/README.md#L184)):*
> ```Markdown
> 
> ### Unreleased
> * Converted appveyor.yml to install Pester from PSGallery instead of from Chocolatey.
> ```

The PR want to remove existing Unreleased section. Maybe a rebase needs to be done?  

---

*[xSCOM.psd1, line 3 at r1](https://reviewable.io/reviews/powershell/xscom/10#-LD1b7D87xz0i70ceZDr:-LD1b7D87xz0i70ceZDs:b-o4wmr8) ([raw file](https://github.com/powershell/xscom/blob/da802bcc20cb2602638120fbfc3bba47897b0766/xSCOM.psd1#L3)):*
> ```PowerShell
> @{
> # Version number of this module.
> ModuleVersion = '1.3.3.0'
> ```

We should not change version number here. It will change during the release.

---

*[xSCOM.psd1, line 33 at r1](https://reviewable.io/reviews/powershell/xscom/10#-LD1bCL733GTWUxdl70A:-LD1bCL733GTWUxdl70B:b-n201a6) ([raw file](https://github.com/powershell/xscom/blob/ca8a55886405955df5705617eecbb9a2c8319453/xSCOM.psd1#L33)):*
> ```PowerShell
> 
> # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
> PrivateData = @{
> ```

This PR removes the PrivateData hashtable  - that should still exist.

---

*[DSCResources/MSFT_xSCOMConsoleSetup/MSFT_xSCOMConsoleSetup.psm1, line 17 at r1](https://reviewable.io/reviews/powershell/xscom/10#-LD1bKfN7OR8yiZpl8ss:-LD1bKfN7OR8yiZpl8st:b-8kihd6) ([raw file](https://github.com/powershell/xscom/blob/da802bcc20cb2602638120fbfc3bba47897b0766/DSCResources/MSFT_xSCOMConsoleSetup/MSFT_xSCOMConsoleSetup.psm1#L17)):*
> ```PowerShell
> 
>         [System.String]
>         $SourceFolder = "\SystemCenter2016\OperationsManager",
> ```

Maybe we should not change the default value? That will break existing configurations.  Throughout this PR.

---

*[DSCResources/MSFT_xSCOMConsoleSetup/MSFT_xSCOMConsoleSetup.psm1, line 54 at r1](https://reviewable.io/reviews/powershell/xscom/10#-LD1bjbz0ncT_J64r8oK:-LD1bjbz0ncT_J64r8oL:b-2bwh5i) ([raw file](https://github.com/powershell/xscom/blob/da802bcc20cb2602638120fbfc3bba47897b0766/DSCResources/MSFT_xSCOMConsoleSetup/MSFT_xSCOMConsoleSetup.psm1#L54)):*
> ```
> "7.2.11719.0"
> ```

This removes build "7.2.10015.0". Was it an earlier build of 2016? Just checking if we need to keep the old and add the new.

---

*[DSCResources/MSFT_xSCOMConsoleUpdate/MSFT_xSCOMConsoleUpdate.psm1, line 28 at r1](https://reviewable.io/reviews/powershell/xscom/10#-LD1cPIn5aalKnjLr0wP:-LD1cPIn5aalKnjLr0wQ:bxw1y3y) ([raw file](https://github.com/powershell/xscom/blob/da802bcc20cb2602638120fbfc3bba47897b0766/DSCResources/MSFT_xSCOMConsoleUpdate/MSFT_xSCOMConsoleUpdate.psm1#L28)):*
> ```PowerShell
>     switch($Version)
>     {
>         <#
> ```

This removes build "7.1.10226.0". Maybe add correct product codes here. Or submit an issue to "Add support for 2016 UR1" and remove this comment block.

---

*[DSCResources/MSFT_xSCOMConsoleUpdate/MSFT_xSCOMConsoleUpdate.psm1, line 108 at r1](https://reviewable.io/reviews/powershell/xscom/10#-LD1ca4L1c-H9hWf--vR:-LD1ca4L1c-H9hWf--vS:b-60myny) ([raw file](https://github.com/powershell/xscom/blob/da802bcc20cb2602638120fbfc3bba47897b0766/DSCResources/MSFT_xSCOMConsoleUpdate/MSFT_xSCOMConsoleUpdate.psm1#L108)):*
> ```PowerShell
>     switch($Version)
>     {
>         <#
> ```

This removes build "7.1.10226.0". We should keep both 7.2 and the one 7.1 here?

---

*[DSCResources/MSFT_xSCOMConsoleUpdate/MSFT_xSCOMConsoleUpdate.psm1, line 111 at r1](https://reviewable.io/reviews/powershell/xscom/10#-LD1chIr9jPXz208IaSC:-LD1chIr9jPXz208IaSD:bqkhr3x) ([raw file](https://github.com/powershell/xscom/blob/da802bcc20cb2602638120fbfc3bba47897b0766/DSCResources/MSFT_xSCOMConsoleUpdate/MSFT_xSCOMConsoleUpdate.psm1#L111)):*
> ```PowerShell
>         "7.2.11759.0"
>         {
>             # Need to add correct update file for UR 1 2016
> ```

This isn't the correct update file?

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xscom/10#-:-LD1d-kK4JPatG-pVC36:b-62o2t6)*

**Comment by mortenlerudjordet** [comment]
Hello, it has been a long time since I did this. Though if I remember correctly the values that was originally set 7.2.10015.0 was for TP5 and not RTM.

I also never tested the update part of the module, therefore I have commented out the changes I added there. I never had the time to verify that it was the correct update codes. Therefore I did not want to make it active.

**Comment by johlju** [comment]
Thanks for the information. Feels a manual integration test need to be run using this PR to verify.

**Comment by mortenlerudjordet** [comment]
I added my install script as an example. It only supports a pre existing SQL instance.

**Comment by Francois-Rousseau** [comment]
I, I want to try to modify the ressource for SCOM 2016, can someone give me some crash course on how to get the code please, I already know the changes I have to do, just want to try and send a PR

**Comment by Francois-Rousseau** [comment]
I have time to work on this one, feel free to tell me what can I do to start from what have already been done by @mortenlerudjordet , @johlju .Thanks!

**Comment by mortenlerudjordet** [comment]
Just  download the changes I have done here: 
https://github.com/mortenlerudjordet/xSCOM
then check if it works when deploying SCOM, if not just do your own fork of the original repo and add the needed changes there.
Then you can do your own pull request against the source.

**Comment by johlju** [comment]
@Francois-Rousseau you can also look here as it should help you out [How to continue working on a pull request (PR) when an author (contributor) is unable to complete it](https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#how-to-continue-working-on-a-pull-request-pr-when-an-author-contributor-is-unable-to-complete-it).

**Pull request closed without merging**
